[phases.setup]
nixPkgs = ["python310", "pip", "gcc", "python310Packages.wheel"]

[phases.install]
cmds = [
  "pip install -r requirements-production.txt",
  "mkdir -p webapp/logs webapp/uploads webapp/knowledge_base webapp/sessions",
  "mkdir -p env_configs"
]

[start]
cmd = "python webapp/app.py"

[variables]
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"